apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  APP_NAME: "Laravel"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://frontend-service:8003"

  LOG_CHANNEL: "stack"
  LOG_LEVEL: "debug"

  AUTH_API_URL: "http://auth-api-service:8000"
  TAREAS_API_URL: "http://tareas-api-service:8001"
  HISTORIAL_API_URL: "http://historial-api-service:8002"
